# ==========================
# Wiki COOPNUM - Site Config
# ==========================

# Thème Jekyll
theme: jekyll-theme-chirpy

# Langue et fuseau
lang: fr
timezone: Europe/Paris

# SEO & métadonnées
title: Wiki COOPNUM
tagline: Le wiki collaboratif de la Coopérative Numérique des 7 Vallées
description: >-
  Ressources, fiches et projets collaboratifs de la COOPNUM.
url: ""   # ← à remplir plus tard avec ton domaine ou GitHub Pages

# Comptes sociaux
github:
  username: coopnum

social:
  name: COOPNUM
  email: contact@coopnum.fr
  links:
    - https://github.com/coopnum

# Analytics (optionnel)
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Mode visuel
theme_mode: # [light | dark] — vide = suit le système
cdn: ""     # optionnel, pour héberger des assets statiques

avatar: "/commons/avatar.jpg"
toc: true

# Commentaires (désactivés par défaut)
comments:
  provider:

# Progressive Web App (PWA)
pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10
baseurl: ""

# ----------------------
# Collections de fiches
# ----------------------
collections:
  actions:
    output: true
    permalink: /actions/:title/
  ateliers:
    output: true
    permalink: /ateliers/:title/
  logiciels:
    output: true
    permalink: /logiciels/:title/
  communautes:
    output: true
    permalink: /communautes/:title/
  jeux:
    output: true
    permalink: /jeux/:title/
  partenaires:
    output: true
    permalink: /partenaires/:title/
  projets:
    output: true
    permalink: /projets/:title/
  lexiques:
    output: true
    permalink: /lexiques/:title/

# ----------------------
# Defaults par collection
# ----------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

  - scope:
      path: ""
      type: actions
    values:
      layout: fiche-action

  - scope:
      path: ""
      type: ateliers
    values:
      layout: fiche-atelier

  - scope:
      path: ""
      type: logiciels
    values:
      layout: fiche-logiciel

  - scope:
      path: ""
      type: communautes
    values:
      layout: fiche-communaute

  - scope:
      path: ""
      type: jeux
    values:
      layout: fiche-jeu

  - scope:
      path: ""
      type: partenaires
    values:
      layout: fiche-partenaire

  - scope:
      path: ""
      type: projets
    values:
      layout: fiche-projet

  - scope:
      path: ""
      type: lexiques
    values:
      layout: fiche-lexique

# ----------------------
# Options techniques
# ----------------------
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
